default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: urls_development
  username: postgres
  password: postgres

test:
  <<: *default
  host: 127.0.0.1
  database: urls_test
  username: postgres
  password: postgres

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
